/* eslint-disable */
import * as types from './graphql.js';
import type { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';

/**
 * Map of all GraphQL operations in the project.
 *
 * This map has several performance disadvantages:
 * 1. It is not tree-shakeable, so it will include all operations in the project.
 * 2. It is not minifiable, so the string of a GraphQL query will be multiple times inside the bundle.
 * 3. It does not support dead code elimination, so it will add unused operations.
 *
 * Therefore it is highly recommended to use the babel or swc plugin for production.
 * Learn more about it here: https://the-guild.dev/graphql/codegen/plugins/presets/preset-client#reducing-bundle-size
 */
type Documents = {
    "\n  mutation CreateRoutineSlot($input: CreateRoutineSlotInput!) {\n    createRoutineSlot(input: $input) {\n      routineSlotEdge {\n        node {\n          id\n          task {\n            id\n            title\n          }\n          dayOfWeek\n          section\n          createdAt\n        }\n        cursor\n      }\n    }\n  }\n": typeof types.CreateRoutineSlotDocument,
    "\n  mutation CompleteRoutineSlotHelper($routineSlotId: ID!) {\n    completeRoutineSlot(routineSlotId: $routineSlotId) {\n      taskCompletionEdge {\n        node {\n          id\n          completedAt\n          routineSlot {\n            id\n            dayOfWeek\n            section\n          }\n        }\n        cursor\n      }\n    }\n  }\n": typeof types.CompleteRoutineSlotHelperDocument,
    "\n  mutation CreateTaskMutation($title: String!, $icon: String) {\n    createTask(title: $title, icon: $icon) {\n      taskEdge {\n        node {\n          id\n          title\n          icon\n        }\n      }\n    }\n  }\n": typeof types.CreateTaskMutationDocument,
    "\n  query NodeQuery($id: ID!) {\n    node(id: $id) {\n      __typename\n      ... on User {\n        id\n        email\n      }\n\n      ... on Task {\n        id\n        title\n      }\n\n      ... on RoutineSlot {\n        id\n        dayOfWeek\n        section\n        task {\n          id\n          title\n        }\n      }\n\n      ... on TaskCompletion {\n        id\n        completedAt\n        routineSlot {\n          id\n          dayOfWeek\n          section\n        }\n      }\n    }\n  }\n": typeof types.NodeQueryDocument,
    "\n        mutation CreateRoutineSlot($input: CreateRoutineSlotInput!) {\n          createRoutineSlot(input: $input) {\n            routineSlotEdge {\n              node {\n                id\n                task {\n                  id\n                  title\n                }\n                dayOfWeek\n                section\n                createdAt\n              }\n              cursor\n            }\n          }\n        }\n      ": typeof types.CreateRoutineSlotDocument,
    "\n        mutation DeleteRoutineSlot($routineSlotId: ID!) {\n          deleteRoutineSlot(routineSlotId: $routineSlotId) {\n            deletedId\n          }\n        }\n      ": typeof types.DeleteRoutineSlotDocument,
    "\n        query TaskResolverQuery {\n          tasks {\n            edges {\n              node {\n                title\n                slots {\n                  edges {\n                    node {\n                      dayOfWeek\n                      section\n                    }\n                  }\n                }\n              }\n            }\n          }\n        }\n      ": typeof types.TaskResolverQueryDocument,
    "\n        query GetDayOfWeek($date: DateTime) {\n          dailyRoutine(date: $date) {\n            dayOfWeek\n          }\n        }\n      ": typeof types.GetDayOfWeekDocument,
    "\n        query DailyRoutineWithSections($date: DateTime) {\n          dailyRoutine(date: $date) {\n            morning {\n              edges {\n                node {\n                  routineSlot {\n                    dayOfWeek\n                    section\n                    task {\n                      title\n                    }\n                  }\n                  completion {\n                    __typename\n                  }\n                }\n              }\n            }\n            midday {\n              edges {\n                node {\n                  routineSlot {\n                    dayOfWeek\n                    section\n                    task {\n                      title\n                    }\n                  }\n                  completion {\n                    __typename\n                  }\n                }\n              }\n            }\n            evening {\n              edges {\n                node {\n                  routineSlot {\n                    dayOfWeek\n                    section\n                    task {\n                      title\n                    }\n                  }\n                  completion {\n                    __typename\n                  }\n                }\n              }\n            }\n          }\n        }\n      ": typeof types.DailyRoutineWithSectionsDocument,
    "\n        query DailyRoutineByDayOfWeek($date: DateTime) {\n          dailyRoutine(date: $date) {\n            dayOfWeek\n            morning {\n              edges {\n                node {\n                  routineSlot {\n                    dayOfWeek\n                  }\n                }\n              }\n            }\n          }\n        }\n      ": typeof types.DailyRoutineByDayOfWeekDocument,
    "\n        query WeeklySchedule {\n          weeklySchedule {\n            monday {\n              dayOfWeek\n              morning {\n                edges {\n                  node {\n                    section\n                    task {\n                      title\n                    }\n                  }\n                }\n              }\n              midday {\n                edges {\n                  __typename\n                }\n              }\n              evening {\n                edges {\n                  __typename\n                }\n              }\n            }\n            tuesday {\n              dayOfWeek\n              morning {\n                edges {\n                  __typename\n                }\n              }\n              midday {\n                edges {\n                  __typename\n                }\n              }\n              evening {\n                edges {\n                  node {\n                    section\n                    task {\n                      title\n                    }\n                  }\n                }\n              }\n            }\n          }\n        }\n      ": typeof types.WeeklyScheduleDocument,
    "\n        mutation CompleteRoutineSlot($routineSlotId: ID!) {\n          completeRoutineSlot(routineSlotId: $routineSlotId) {\n            taskCompletionEdge {\n              node {\n                id\n                completedAt\n                routineSlot {\n                  id\n                  task {\n                    id\n                    title\n                  }\n                }\n              }\n              cursor\n            }\n          }\n        }\n      ": typeof types.CompleteRoutineSlotDocument,
    "\n        mutation CompleteRoutineSlotForUncompletion($routineSlotId: ID!) {\n          completeRoutineSlot(routineSlotId: $routineSlotId) {\n            taskCompletionEdge {\n              node {\n                id\n              }\n            }\n          }\n        }\n      ": typeof types.CompleteRoutineSlotForUncompletionDocument,
    "\n        mutation UncompleteRoutineSlot($taskCompletionId: ID!) {\n          uncompleteRoutineSlot(taskCompletionId: $taskCompletionId) {\n            deletedId\n          }\n        }\n      ": typeof types.UncompleteRoutineSlotDocument,
    "\n        mutation FirstCompletion($routineSlotId: ID!) {\n          completeRoutineSlot(routineSlotId: $routineSlotId) {\n            taskCompletionEdge {\n              node {\n                id\n              }\n            }\n          }\n        }\n      ": typeof types.FirstCompletionDocument,
    "\n        mutation SecondCompletion($routineSlotId: ID!) {\n          completeRoutineSlot(routineSlotId: $routineSlotId) {\n            taskCompletionEdge {\n              node {\n                id\n              }\n            }\n          }\n        }\n      ": typeof types.SecondCompletionDocument,
    "\n        mutation CompleteForTaskCompletionsTest($routineSlotId: ID!) {\n          completeRoutineSlot(routineSlotId: $routineSlotId) {\n            taskCompletionEdge {\n              node {\n                id\n              }\n            }\n          }\n        }\n      ": typeof types.CompleteForTaskCompletionsTestDocument,
    "\n        query TaskCompletionsResolverQuery {\n          tasks {\n            edges {\n              node {\n                title\n                completions {\n                  edges {\n                    node {\n                      id\n                      completedAt\n                      routineSlot {\n                        dayOfWeek\n                        section\n                      }\n                    }\n                  }\n                }\n              }\n            }\n          }\n        }\n      ": typeof types.TaskCompletionsResolverQueryDocument,
    "\n        mutation UpdateTask($input: UpdateTaskInput!) {\n          updateTask(input: $input) {\n            task {\n              id\n              title\n            }\n          }\n        }\n      ": typeof types.UpdateTaskDocument,
    "\n        mutation UpdateTaskIcon($input: UpdateTaskInput!) {\n          updateTask(input: $input) {\n            task {\n              id\n              title\n              icon\n            }\n          }\n        }\n      ": typeof types.UpdateTaskIconDocument,
    "\n        mutation DeleteTask($taskId: ID!) {\n          deleteTask(taskId: $taskId) {\n            deletedId\n          }\n        }\n      ": typeof types.DeleteTaskDocument,
    "\n        query TasksTestOne {\n          tasks(first: 1) {\n            edges {\n              node {\n                title\n              }\n            }\n          }\n        }\n      ": typeof types.TasksTestOneDocument,
    "\n      query PaginatedTasks($after: String) {\n        tasks(first: 10, after: $after) {\n          edges {\n            node {\n              id\n              title\n            }\n          }\n          pageInfo {\n            hasNextPage\n            endCursor\n            startCursor\n          }\n        }\n      }\n    ": typeof types.PaginatedTasksDocument,
    "\n        query TasksTitleSearch($titleSearch: String) {\n          tasks(first: 10, titleSearch: $titleSearch) {\n            edges {\n              node {\n                title\n              }\n            }\n          }\n        }\n      ": typeof types.TasksTitleSearchDocument,
    "\n        query TasksTitleSearchCaseInsensitive($titleSearch: String) {\n          tasks(first: 10, titleSearch: $titleSearch) {\n            edges {\n              node {\n                title\n              }\n            }\n          }\n        }\n      ": typeof types.TasksTitleSearchCaseInsensitiveDocument,
    "\n        query TasksNoTitleSearch {\n          tasks(first: 10) {\n            edges {\n              node {\n                title\n              }\n            }\n          }\n        }\n      ": typeof types.TasksNoTitleSearchDocument,
};
const documents: Documents = {
    "\n  mutation CreateRoutineSlot($input: CreateRoutineSlotInput!) {\n    createRoutineSlot(input: $input) {\n      routineSlotEdge {\n        node {\n          id\n          task {\n            id\n            title\n          }\n          dayOfWeek\n          section\n          createdAt\n        }\n        cursor\n      }\n    }\n  }\n": types.CreateRoutineSlotDocument,
    "\n  mutation CompleteRoutineSlotHelper($routineSlotId: ID!) {\n    completeRoutineSlot(routineSlotId: $routineSlotId) {\n      taskCompletionEdge {\n        node {\n          id\n          completedAt\n          routineSlot {\n            id\n            dayOfWeek\n            section\n          }\n        }\n        cursor\n      }\n    }\n  }\n": types.CompleteRoutineSlotHelperDocument,
    "\n  mutation CreateTaskMutation($title: String!, $icon: String) {\n    createTask(title: $title, icon: $icon) {\n      taskEdge {\n        node {\n          id\n          title\n          icon\n        }\n      }\n    }\n  }\n": types.CreateTaskMutationDocument,
    "\n  query NodeQuery($id: ID!) {\n    node(id: $id) {\n      __typename\n      ... on User {\n        id\n        email\n      }\n\n      ... on Task {\n        id\n        title\n      }\n\n      ... on RoutineSlot {\n        id\n        dayOfWeek\n        section\n        task {\n          id\n          title\n        }\n      }\n\n      ... on TaskCompletion {\n        id\n        completedAt\n        routineSlot {\n          id\n          dayOfWeek\n          section\n        }\n      }\n    }\n  }\n": types.NodeQueryDocument,
    "\n        mutation CreateRoutineSlot($input: CreateRoutineSlotInput!) {\n          createRoutineSlot(input: $input) {\n            routineSlotEdge {\n              node {\n                id\n                task {\n                  id\n                  title\n                }\n                dayOfWeek\n                section\n                createdAt\n              }\n              cursor\n            }\n          }\n        }\n      ": types.CreateRoutineSlotDocument,
    "\n        mutation DeleteRoutineSlot($routineSlotId: ID!) {\n          deleteRoutineSlot(routineSlotId: $routineSlotId) {\n            deletedId\n          }\n        }\n      ": types.DeleteRoutineSlotDocument,
    "\n        query TaskResolverQuery {\n          tasks {\n            edges {\n              node {\n                title\n                slots {\n                  edges {\n                    node {\n                      dayOfWeek\n                      section\n                    }\n                  }\n                }\n              }\n            }\n          }\n        }\n      ": types.TaskResolverQueryDocument,
    "\n        query GetDayOfWeek($date: DateTime) {\n          dailyRoutine(date: $date) {\n            dayOfWeek\n          }\n        }\n      ": types.GetDayOfWeekDocument,
    "\n        query DailyRoutineWithSections($date: DateTime) {\n          dailyRoutine(date: $date) {\n            morning {\n              edges {\n                node {\n                  routineSlot {\n                    dayOfWeek\n                    section\n                    task {\n                      title\n                    }\n                  }\n                  completion {\n                    __typename\n                  }\n                }\n              }\n            }\n            midday {\n              edges {\n                node {\n                  routineSlot {\n                    dayOfWeek\n                    section\n                    task {\n                      title\n                    }\n                  }\n                  completion {\n                    __typename\n                  }\n                }\n              }\n            }\n            evening {\n              edges {\n                node {\n                  routineSlot {\n                    dayOfWeek\n                    section\n                    task {\n                      title\n                    }\n                  }\n                  completion {\n                    __typename\n                  }\n                }\n              }\n            }\n          }\n        }\n      ": types.DailyRoutineWithSectionsDocument,
    "\n        query DailyRoutineByDayOfWeek($date: DateTime) {\n          dailyRoutine(date: $date) {\n            dayOfWeek\n            morning {\n              edges {\n                node {\n                  routineSlot {\n                    dayOfWeek\n                  }\n                }\n              }\n            }\n          }\n        }\n      ": types.DailyRoutineByDayOfWeekDocument,
    "\n        query WeeklySchedule {\n          weeklySchedule {\n            monday {\n              dayOfWeek\n              morning {\n                edges {\n                  node {\n                    section\n                    task {\n                      title\n                    }\n                  }\n                }\n              }\n              midday {\n                edges {\n                  __typename\n                }\n              }\n              evening {\n                edges {\n                  __typename\n                }\n              }\n            }\n            tuesday {\n              dayOfWeek\n              morning {\n                edges {\n                  __typename\n                }\n              }\n              midday {\n                edges {\n                  __typename\n                }\n              }\n              evening {\n                edges {\n                  node {\n                    section\n                    task {\n                      title\n                    }\n                  }\n                }\n              }\n            }\n          }\n        }\n      ": types.WeeklyScheduleDocument,
    "\n        mutation CompleteRoutineSlot($routineSlotId: ID!) {\n          completeRoutineSlot(routineSlotId: $routineSlotId) {\n            taskCompletionEdge {\n              node {\n                id\n                completedAt\n                routineSlot {\n                  id\n                  task {\n                    id\n                    title\n                  }\n                }\n              }\n              cursor\n            }\n          }\n        }\n      ": types.CompleteRoutineSlotDocument,
    "\n        mutation CompleteRoutineSlotForUncompletion($routineSlotId: ID!) {\n          completeRoutineSlot(routineSlotId: $routineSlotId) {\n            taskCompletionEdge {\n              node {\n                id\n              }\n            }\n          }\n        }\n      ": types.CompleteRoutineSlotForUncompletionDocument,
    "\n        mutation UncompleteRoutineSlot($taskCompletionId: ID!) {\n          uncompleteRoutineSlot(taskCompletionId: $taskCompletionId) {\n            deletedId\n          }\n        }\n      ": types.UncompleteRoutineSlotDocument,
    "\n        mutation FirstCompletion($routineSlotId: ID!) {\n          completeRoutineSlot(routineSlotId: $routineSlotId) {\n            taskCompletionEdge {\n              node {\n                id\n              }\n            }\n          }\n        }\n      ": types.FirstCompletionDocument,
    "\n        mutation SecondCompletion($routineSlotId: ID!) {\n          completeRoutineSlot(routineSlotId: $routineSlotId) {\n            taskCompletionEdge {\n              node {\n                id\n              }\n            }\n          }\n        }\n      ": types.SecondCompletionDocument,
    "\n        mutation CompleteForTaskCompletionsTest($routineSlotId: ID!) {\n          completeRoutineSlot(routineSlotId: $routineSlotId) {\n            taskCompletionEdge {\n              node {\n                id\n              }\n            }\n          }\n        }\n      ": types.CompleteForTaskCompletionsTestDocument,
    "\n        query TaskCompletionsResolverQuery {\n          tasks {\n            edges {\n              node {\n                title\n                completions {\n                  edges {\n                    node {\n                      id\n                      completedAt\n                      routineSlot {\n                        dayOfWeek\n                        section\n                      }\n                    }\n                  }\n                }\n              }\n            }\n          }\n        }\n      ": types.TaskCompletionsResolverQueryDocument,
    "\n        mutation UpdateTask($input: UpdateTaskInput!) {\n          updateTask(input: $input) {\n            task {\n              id\n              title\n            }\n          }\n        }\n      ": types.UpdateTaskDocument,
    "\n        mutation UpdateTaskIcon($input: UpdateTaskInput!) {\n          updateTask(input: $input) {\n            task {\n              id\n              title\n              icon\n            }\n          }\n        }\n      ": types.UpdateTaskIconDocument,
    "\n        mutation DeleteTask($taskId: ID!) {\n          deleteTask(taskId: $taskId) {\n            deletedId\n          }\n        }\n      ": types.DeleteTaskDocument,
    "\n        query TasksTestOne {\n          tasks(first: 1) {\n            edges {\n              node {\n                title\n              }\n            }\n          }\n        }\n      ": types.TasksTestOneDocument,
    "\n      query PaginatedTasks($after: String) {\n        tasks(first: 10, after: $after) {\n          edges {\n            node {\n              id\n              title\n            }\n          }\n          pageInfo {\n            hasNextPage\n            endCursor\n            startCursor\n          }\n        }\n      }\n    ": types.PaginatedTasksDocument,
    "\n        query TasksTitleSearch($titleSearch: String) {\n          tasks(first: 10, titleSearch: $titleSearch) {\n            edges {\n              node {\n                title\n              }\n            }\n          }\n        }\n      ": types.TasksTitleSearchDocument,
    "\n        query TasksTitleSearchCaseInsensitive($titleSearch: String) {\n          tasks(first: 10, titleSearch: $titleSearch) {\n            edges {\n              node {\n                title\n              }\n            }\n          }\n        }\n      ": types.TasksTitleSearchCaseInsensitiveDocument,
    "\n        query TasksNoTitleSearch {\n          tasks(first: 10) {\n            edges {\n              node {\n                title\n              }\n            }\n          }\n        }\n      ": types.TasksNoTitleSearchDocument,
};

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 *
 *
 * @example
 * ```ts
 * const query = graphql(`query GetUser($id: ID!) { user(id: $id) { name } }`);
 * ```
 *
 * The query argument is unknown!
 * Please regenerate the types.
 */
export function graphql(source: string): unknown;

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation CreateRoutineSlot($input: CreateRoutineSlotInput!) {\n    createRoutineSlot(input: $input) {\n      routineSlotEdge {\n        node {\n          id\n          task {\n            id\n            title\n          }\n          dayOfWeek\n          section\n          createdAt\n        }\n        cursor\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation CreateRoutineSlot($input: CreateRoutineSlotInput!) {\n    createRoutineSlot(input: $input) {\n      routineSlotEdge {\n        node {\n          id\n          task {\n            id\n            title\n          }\n          dayOfWeek\n          section\n          createdAt\n        }\n        cursor\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation CompleteRoutineSlotHelper($routineSlotId: ID!) {\n    completeRoutineSlot(routineSlotId: $routineSlotId) {\n      taskCompletionEdge {\n        node {\n          id\n          completedAt\n          routineSlot {\n            id\n            dayOfWeek\n            section\n          }\n        }\n        cursor\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation CompleteRoutineSlotHelper($routineSlotId: ID!) {\n    completeRoutineSlot(routineSlotId: $routineSlotId) {\n      taskCompletionEdge {\n        node {\n          id\n          completedAt\n          routineSlot {\n            id\n            dayOfWeek\n            section\n          }\n        }\n        cursor\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation CreateTaskMutation($title: String!, $icon: String) {\n    createTask(title: $title, icon: $icon) {\n      taskEdge {\n        node {\n          id\n          title\n          icon\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation CreateTaskMutation($title: String!, $icon: String) {\n    createTask(title: $title, icon: $icon) {\n      taskEdge {\n        node {\n          id\n          title\n          icon\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query NodeQuery($id: ID!) {\n    node(id: $id) {\n      __typename\n      ... on User {\n        id\n        email\n      }\n\n      ... on Task {\n        id\n        title\n      }\n\n      ... on RoutineSlot {\n        id\n        dayOfWeek\n        section\n        task {\n          id\n          title\n        }\n      }\n\n      ... on TaskCompletion {\n        id\n        completedAt\n        routineSlot {\n          id\n          dayOfWeek\n          section\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query NodeQuery($id: ID!) {\n    node(id: $id) {\n      __typename\n      ... on User {\n        id\n        email\n      }\n\n      ... on Task {\n        id\n        title\n      }\n\n      ... on RoutineSlot {\n        id\n        dayOfWeek\n        section\n        task {\n          id\n          title\n        }\n      }\n\n      ... on TaskCompletion {\n        id\n        completedAt\n        routineSlot {\n          id\n          dayOfWeek\n          section\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n        mutation CreateRoutineSlot($input: CreateRoutineSlotInput!) {\n          createRoutineSlot(input: $input) {\n            routineSlotEdge {\n              node {\n                id\n                task {\n                  id\n                  title\n                }\n                dayOfWeek\n                section\n                createdAt\n              }\n              cursor\n            }\n          }\n        }\n      "): (typeof documents)["\n        mutation CreateRoutineSlot($input: CreateRoutineSlotInput!) {\n          createRoutineSlot(input: $input) {\n            routineSlotEdge {\n              node {\n                id\n                task {\n                  id\n                  title\n                }\n                dayOfWeek\n                section\n                createdAt\n              }\n              cursor\n            }\n          }\n        }\n      "];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n        mutation DeleteRoutineSlot($routineSlotId: ID!) {\n          deleteRoutineSlot(routineSlotId: $routineSlotId) {\n            deletedId\n          }\n        }\n      "): (typeof documents)["\n        mutation DeleteRoutineSlot($routineSlotId: ID!) {\n          deleteRoutineSlot(routineSlotId: $routineSlotId) {\n            deletedId\n          }\n        }\n      "];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n        query TaskResolverQuery {\n          tasks {\n            edges {\n              node {\n                title\n                slots {\n                  edges {\n                    node {\n                      dayOfWeek\n                      section\n                    }\n                  }\n                }\n              }\n            }\n          }\n        }\n      "): (typeof documents)["\n        query TaskResolverQuery {\n          tasks {\n            edges {\n              node {\n                title\n                slots {\n                  edges {\n                    node {\n                      dayOfWeek\n                      section\n                    }\n                  }\n                }\n              }\n            }\n          }\n        }\n      "];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n        query GetDayOfWeek($date: DateTime) {\n          dailyRoutine(date: $date) {\n            dayOfWeek\n          }\n        }\n      "): (typeof documents)["\n        query GetDayOfWeek($date: DateTime) {\n          dailyRoutine(date: $date) {\n            dayOfWeek\n          }\n        }\n      "];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n        query DailyRoutineWithSections($date: DateTime) {\n          dailyRoutine(date: $date) {\n            morning {\n              edges {\n                node {\n                  routineSlot {\n                    dayOfWeek\n                    section\n                    task {\n                      title\n                    }\n                  }\n                  completion {\n                    __typename\n                  }\n                }\n              }\n            }\n            midday {\n              edges {\n                node {\n                  routineSlot {\n                    dayOfWeek\n                    section\n                    task {\n                      title\n                    }\n                  }\n                  completion {\n                    __typename\n                  }\n                }\n              }\n            }\n            evening {\n              edges {\n                node {\n                  routineSlot {\n                    dayOfWeek\n                    section\n                    task {\n                      title\n                    }\n                  }\n                  completion {\n                    __typename\n                  }\n                }\n              }\n            }\n          }\n        }\n      "): (typeof documents)["\n        query DailyRoutineWithSections($date: DateTime) {\n          dailyRoutine(date: $date) {\n            morning {\n              edges {\n                node {\n                  routineSlot {\n                    dayOfWeek\n                    section\n                    task {\n                      title\n                    }\n                  }\n                  completion {\n                    __typename\n                  }\n                }\n              }\n            }\n            midday {\n              edges {\n                node {\n                  routineSlot {\n                    dayOfWeek\n                    section\n                    task {\n                      title\n                    }\n                  }\n                  completion {\n                    __typename\n                  }\n                }\n              }\n            }\n            evening {\n              edges {\n                node {\n                  routineSlot {\n                    dayOfWeek\n                    section\n                    task {\n                      title\n                    }\n                  }\n                  completion {\n                    __typename\n                  }\n                }\n              }\n            }\n          }\n        }\n      "];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n        query DailyRoutineByDayOfWeek($date: DateTime) {\n          dailyRoutine(date: $date) {\n            dayOfWeek\n            morning {\n              edges {\n                node {\n                  routineSlot {\n                    dayOfWeek\n                  }\n                }\n              }\n            }\n          }\n        }\n      "): (typeof documents)["\n        query DailyRoutineByDayOfWeek($date: DateTime) {\n          dailyRoutine(date: $date) {\n            dayOfWeek\n            morning {\n              edges {\n                node {\n                  routineSlot {\n                    dayOfWeek\n                  }\n                }\n              }\n            }\n          }\n        }\n      "];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n        query WeeklySchedule {\n          weeklySchedule {\n            monday {\n              dayOfWeek\n              morning {\n                edges {\n                  node {\n                    section\n                    task {\n                      title\n                    }\n                  }\n                }\n              }\n              midday {\n                edges {\n                  __typename\n                }\n              }\n              evening {\n                edges {\n                  __typename\n                }\n              }\n            }\n            tuesday {\n              dayOfWeek\n              morning {\n                edges {\n                  __typename\n                }\n              }\n              midday {\n                edges {\n                  __typename\n                }\n              }\n              evening {\n                edges {\n                  node {\n                    section\n                    task {\n                      title\n                    }\n                  }\n                }\n              }\n            }\n          }\n        }\n      "): (typeof documents)["\n        query WeeklySchedule {\n          weeklySchedule {\n            monday {\n              dayOfWeek\n              morning {\n                edges {\n                  node {\n                    section\n                    task {\n                      title\n                    }\n                  }\n                }\n              }\n              midday {\n                edges {\n                  __typename\n                }\n              }\n              evening {\n                edges {\n                  __typename\n                }\n              }\n            }\n            tuesday {\n              dayOfWeek\n              morning {\n                edges {\n                  __typename\n                }\n              }\n              midday {\n                edges {\n                  __typename\n                }\n              }\n              evening {\n                edges {\n                  node {\n                    section\n                    task {\n                      title\n                    }\n                  }\n                }\n              }\n            }\n          }\n        }\n      "];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n        mutation CompleteRoutineSlot($routineSlotId: ID!) {\n          completeRoutineSlot(routineSlotId: $routineSlotId) {\n            taskCompletionEdge {\n              node {\n                id\n                completedAt\n                routineSlot {\n                  id\n                  task {\n                    id\n                    title\n                  }\n                }\n              }\n              cursor\n            }\n          }\n        }\n      "): (typeof documents)["\n        mutation CompleteRoutineSlot($routineSlotId: ID!) {\n          completeRoutineSlot(routineSlotId: $routineSlotId) {\n            taskCompletionEdge {\n              node {\n                id\n                completedAt\n                routineSlot {\n                  id\n                  task {\n                    id\n                    title\n                  }\n                }\n              }\n              cursor\n            }\n          }\n        }\n      "];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n        mutation CompleteRoutineSlotForUncompletion($routineSlotId: ID!) {\n          completeRoutineSlot(routineSlotId: $routineSlotId) {\n            taskCompletionEdge {\n              node {\n                id\n              }\n            }\n          }\n        }\n      "): (typeof documents)["\n        mutation CompleteRoutineSlotForUncompletion($routineSlotId: ID!) {\n          completeRoutineSlot(routineSlotId: $routineSlotId) {\n            taskCompletionEdge {\n              node {\n                id\n              }\n            }\n          }\n        }\n      "];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n        mutation UncompleteRoutineSlot($taskCompletionId: ID!) {\n          uncompleteRoutineSlot(taskCompletionId: $taskCompletionId) {\n            deletedId\n          }\n        }\n      "): (typeof documents)["\n        mutation UncompleteRoutineSlot($taskCompletionId: ID!) {\n          uncompleteRoutineSlot(taskCompletionId: $taskCompletionId) {\n            deletedId\n          }\n        }\n      "];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n        mutation FirstCompletion($routineSlotId: ID!) {\n          completeRoutineSlot(routineSlotId: $routineSlotId) {\n            taskCompletionEdge {\n              node {\n                id\n              }\n            }\n          }\n        }\n      "): (typeof documents)["\n        mutation FirstCompletion($routineSlotId: ID!) {\n          completeRoutineSlot(routineSlotId: $routineSlotId) {\n            taskCompletionEdge {\n              node {\n                id\n              }\n            }\n          }\n        }\n      "];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n        mutation SecondCompletion($routineSlotId: ID!) {\n          completeRoutineSlot(routineSlotId: $routineSlotId) {\n            taskCompletionEdge {\n              node {\n                id\n              }\n            }\n          }\n        }\n      "): (typeof documents)["\n        mutation SecondCompletion($routineSlotId: ID!) {\n          completeRoutineSlot(routineSlotId: $routineSlotId) {\n            taskCompletionEdge {\n              node {\n                id\n              }\n            }\n          }\n        }\n      "];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n        mutation CompleteForTaskCompletionsTest($routineSlotId: ID!) {\n          completeRoutineSlot(routineSlotId: $routineSlotId) {\n            taskCompletionEdge {\n              node {\n                id\n              }\n            }\n          }\n        }\n      "): (typeof documents)["\n        mutation CompleteForTaskCompletionsTest($routineSlotId: ID!) {\n          completeRoutineSlot(routineSlotId: $routineSlotId) {\n            taskCompletionEdge {\n              node {\n                id\n              }\n            }\n          }\n        }\n      "];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n        query TaskCompletionsResolverQuery {\n          tasks {\n            edges {\n              node {\n                title\n                completions {\n                  edges {\n                    node {\n                      id\n                      completedAt\n                      routineSlot {\n                        dayOfWeek\n                        section\n                      }\n                    }\n                  }\n                }\n              }\n            }\n          }\n        }\n      "): (typeof documents)["\n        query TaskCompletionsResolverQuery {\n          tasks {\n            edges {\n              node {\n                title\n                completions {\n                  edges {\n                    node {\n                      id\n                      completedAt\n                      routineSlot {\n                        dayOfWeek\n                        section\n                      }\n                    }\n                  }\n                }\n              }\n            }\n          }\n        }\n      "];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n        mutation UpdateTask($input: UpdateTaskInput!) {\n          updateTask(input: $input) {\n            task {\n              id\n              title\n            }\n          }\n        }\n      "): (typeof documents)["\n        mutation UpdateTask($input: UpdateTaskInput!) {\n          updateTask(input: $input) {\n            task {\n              id\n              title\n            }\n          }\n        }\n      "];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n        mutation UpdateTaskIcon($input: UpdateTaskInput!) {\n          updateTask(input: $input) {\n            task {\n              id\n              title\n              icon\n            }\n          }\n        }\n      "): (typeof documents)["\n        mutation UpdateTaskIcon($input: UpdateTaskInput!) {\n          updateTask(input: $input) {\n            task {\n              id\n              title\n              icon\n            }\n          }\n        }\n      "];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n        mutation DeleteTask($taskId: ID!) {\n          deleteTask(taskId: $taskId) {\n            deletedId\n          }\n        }\n      "): (typeof documents)["\n        mutation DeleteTask($taskId: ID!) {\n          deleteTask(taskId: $taskId) {\n            deletedId\n          }\n        }\n      "];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n        query TasksTestOne {\n          tasks(first: 1) {\n            edges {\n              node {\n                title\n              }\n            }\n          }\n        }\n      "): (typeof documents)["\n        query TasksTestOne {\n          tasks(first: 1) {\n            edges {\n              node {\n                title\n              }\n            }\n          }\n        }\n      "];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n      query PaginatedTasks($after: String) {\n        tasks(first: 10, after: $after) {\n          edges {\n            node {\n              id\n              title\n            }\n          }\n          pageInfo {\n            hasNextPage\n            endCursor\n            startCursor\n          }\n        }\n      }\n    "): (typeof documents)["\n      query PaginatedTasks($after: String) {\n        tasks(first: 10, after: $after) {\n          edges {\n            node {\n              id\n              title\n            }\n          }\n          pageInfo {\n            hasNextPage\n            endCursor\n            startCursor\n          }\n        }\n      }\n    "];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n        query TasksTitleSearch($titleSearch: String) {\n          tasks(first: 10, titleSearch: $titleSearch) {\n            edges {\n              node {\n                title\n              }\n            }\n          }\n        }\n      "): (typeof documents)["\n        query TasksTitleSearch($titleSearch: String) {\n          tasks(first: 10, titleSearch: $titleSearch) {\n            edges {\n              node {\n                title\n              }\n            }\n          }\n        }\n      "];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n        query TasksTitleSearchCaseInsensitive($titleSearch: String) {\n          tasks(first: 10, titleSearch: $titleSearch) {\n            edges {\n              node {\n                title\n              }\n            }\n          }\n        }\n      "): (typeof documents)["\n        query TasksTitleSearchCaseInsensitive($titleSearch: String) {\n          tasks(first: 10, titleSearch: $titleSearch) {\n            edges {\n              node {\n                title\n              }\n            }\n          }\n        }\n      "];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n        query TasksNoTitleSearch {\n          tasks(first: 10) {\n            edges {\n              node {\n                title\n              }\n            }\n          }\n        }\n      "): (typeof documents)["\n        query TasksNoTitleSearch {\n          tasks(first: 10) {\n            edges {\n              node {\n                title\n              }\n            }\n          }\n        }\n      "];

export function graphql(source: string) {
  return (documents as any)[source] ?? {};
}

export type DocumentType<TDocumentNode extends DocumentNode<any, any>> = TDocumentNode extends DocumentNode<  infer TType,  any>  ? TType  : never;