import {
  Activity,
  AlarmClock,
  Apple,
  Bath,
  Bed,
  Bell,
  Bike,
  Book,
  BookOpen,
  Brain,
  Briefcase,
  Calendar,
  Camera,
  Car,
  Carrot,
  CircleCheck,
  ClipboardList,
  Clock,
  Cloud,
  Coffee,
  Compass,
  Cookie,
  Dumbbell,
  FileText,
  Film,
  Flag,
  Folder,
  Footprints,
  Gamepad2,
  Gift,
  GlassWater,
  GraduationCap,
  Hammer,
  Hand,
  Headphones,
  Heart,
  HeartPulse,
  House,
  Laptop,
  Lightbulb,
  ListTodo,
  Mail,
  MapPin,
  MessageCircle,
  Mic,
  Monitor,
  Moon,
  Mountain,
  Music,
  Paintbrush,
  Palette,
  Pencil,
  PenTool,
  PersonStanding,
  Phone,
  Pill,
  Pizza,
  Plane,
  ShoppingBag,
  ShoppingCart,
  ShowerHead,
  Smile,
  Soup,
  Sparkles,
  Star,
  Sun,
  Sunrise,
  Sunset,
  Target,
  Trash2,
  TreePine,
  User,
  Users,
  Utensils,
  WashingMachine,
  Waves,
  Wrench,
  Zap,
  type LucideIcon,
} from 'lucide-react'

export const DEFAULT_ICON_NAME = 'list-todo'

export const iconRegistry = {
  activity: Activity,
  'alarm-clock': AlarmClock,
  apple: Apple,
  bath: Bath,
  bed: Bed,
  bell: Bell,
  bike: Bike,
  book: Book,
  'book-open': BookOpen,
  brain: Brain,
  briefcase: Briefcase,
  calendar: Calendar,
  camera: Camera,
  car: Car,
  carrot: Carrot,
  'circle-check': CircleCheck,
  'clipboard-list': ClipboardList,
  clock: Clock,
  cloud: Cloud,
  coffee: Coffee,
  compass: Compass,
  cookie: Cookie,
  dumbbell: Dumbbell,
  'file-text': FileText,
  film: Film,
  flag: Flag,
  folder: Folder,
  footprints: Footprints,
  'gamepad-2': Gamepad2,
  gift: Gift,
  'glass-water': GlassWater,
  'graduation-cap': GraduationCap,
  hammer: Hammer,
  hand: Hand,
  headphones: Headphones,
  heart: Heart,
  'heart-pulse': HeartPulse,
  house: House,
  laptop: Laptop,
  lightbulb: Lightbulb,
  'list-todo': ListTodo,
  mail: Mail,
  'map-pin': MapPin,
  'message-circle': MessageCircle,
  mic: Mic,
  monitor: Monitor,
  moon: Moon,
  mountain: Mountain,
  music: Music,
  paintbrush: Paintbrush,
  palette: Palette,
  pencil: Pencil,
  'pen-tool': PenTool,
  'person-standing': PersonStanding,
  phone: Phone,
  pill: Pill,
  pizza: Pizza,
  plane: Plane,
  'shopping-bag': ShoppingBag,
  'shopping-cart': ShoppingCart,
  'shower-head': ShowerHead,
  smile: Smile,
  soup: Soup,
  sparkles: Sparkles,
  star: Star,
  sun: Sun,
  sunrise: Sunrise,
  sunset: Sunset,
  target: Target,
  'trash-2': Trash2,
  'tree-pine': TreePine,
  user: User,
  users: Users,
  utensils: Utensils,
  'washing-machine': WashingMachine,
  waves: Waves,
  wrench: Wrench,
  zap: Zap,
} as const satisfies Record<string, LucideIcon>

export type IconName = keyof typeof iconRegistry

export const iconCategories: { label: string; icons: IconName[] }[] = [
  {
    label: 'Health & Fitness',
    icons: [
      'dumbbell',
      'heart-pulse',
      'bike',
      'footprints',
      'activity',
      'person-standing',
      'mountain',
      'waves',
      'pill',
    ],
  },
  {
    label: 'Hygiene',
    icons: ['bath', 'shower-head', 'sparkles', 'hand', 'smile'],
  },
  {
    label: 'Sleep',
    icons: ['bed', 'moon', 'sunrise', 'sunset', 'alarm-clock'],
  },
  {
    label: 'Meals',
    icons: [
      'coffee',
      'utensils',
      'apple',
      'soup',
      'glass-water',
      'carrot',
      'pizza',
      'cookie',
    ],
  },
  {
    label: 'Work',
    icons: [
      'briefcase',
      'laptop',
      'monitor',
      'mail',
      'calendar',
      'clock',
      'clipboard-list',
      'file-text',
      'folder',
    ],
  },
  {
    label: 'Learning',
    icons: [
      'book',
      'book-open',
      'graduation-cap',
      'pencil',
      'pen-tool',
      'lightbulb',
      'brain',
    ],
  },
  {
    label: 'Home & Chores',
    icons: [
      'house',
      'washing-machine',
      'trash-2',
      'shopping-cart',
      'shopping-bag',
      'wrench',
      'hammer',
    ],
  },
  {
    label: 'Social',
    icons: ['phone', 'message-circle', 'users', 'user', 'heart', 'gift'],
  },
  {
    label: 'Creative',
    icons: [
      'music',
      'paintbrush',
      'camera',
      'gamepad-2',
      'headphones',
      'mic',
      'film',
      'palette',
    ],
  },
  {
    label: 'Outdoors',
    icons: ['car', 'plane', 'map-pin', 'tree-pine', 'sun', 'cloud', 'compass'],
  },
  {
    label: 'General',
    icons: ['list-todo', 'circle-check', 'star', 'bell', 'flag', 'target', 'zap'],
  },
]

export const iconNameSet = new Set<string>(Object.keys(iconRegistry))

export const isValidIconName = (name: string): name is IconName =>
  iconNameSet.has(name)

export const parseIconName = (name: string | null | undefined): IconName =>
  name && isValidIconName(name) ? name : DEFAULT_ICON_NAME

export const iconComponent = (name: string | null | undefined): LucideIcon =>
  iconRegistry[parseIconName(name)]

export const iconLabel = (name: IconName): string =>
  name
    .split('-')
    .map(part => part.charAt(0).toUpperCase() + part.slice(1))
    .join(' ')
